---
sudo: required

env:
  - >
    container_id=$(mktemp)
    distribution=centos
    version=7
    init=/usr/lib/systemd/systemd
    run_opts="--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - >
    container_id=$(mktemp)
    distribution=ubuntu
    version=14.04
    init=/sbin/init
    run_opts=""

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo docker pull ${distribution}:${version}
  - >
    sudo docker build --rm=true
    --file=tests/Dockerfile.${distribution}
    --tag=${distribution}:ansible tests

before_script:
  - printf '{"role_name":"Rocket.Chat.Ansible","host_name":"localhost"}' > /tmp/extra_vars

script:

    # Run container in detached state
  - sudo docker run --detach --volume="${PWD}":/etc/ansible/roles/Rocket.Chat.Ansible:ro ${run_opts} ${distribution}:ansible "${init}" > "${container_id}"

    # Syntax check
  - sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/Rocket.Chat.Ansible/tests/provision.yml --syntax-check --extra-vars="$(cat /tmp/extra_vars)"
    # Test role
  - sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/Rocket.Chat.Ansible/tests/provision.yml --extra-vars="$(cat /tmp/extra_vars)"
    # Idempotence test
  - >
    sudo docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/Rocket.Chat.Ansible/tests/provision.yml --extra-vars="$(cat /tmp/extra_vars)"
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

    # Clean up
  - sudo docker stop "$(cat ${container_id})"


notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
