---
# tasks/mongodb.yml: MongoDB configuration for RocketChat.Ansible
  - name: Ensure the MongoDB repository key has been imported
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: 7F0CEB10
    when: ansible_distribution == "Ubuntu"
    tags: repo

  - name: Ensure the MongoDB repository is present
    apt_repository:
      repo: deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 multiverse
      state: present
    when: ansible_distribution == "Ubuntu"
    tags: repo

  - name: Ensure MongoDB Server is present
    yum: name={{ item }} state=present
    with_items: "{{ rocket_chat_mongodb_packages }}"
    when: ansible_os_family == "RedHat"

  - name: Ensure MongoDB Server is present
    apt: name={{ item }} state=present
    with_items: "{{ rocket_chat_mongodb_packages }}"
    when: ansible_os_family == "Debian"

  - name: Check to see if this is the intial MongoDB setup
    stat: path=/var/log/rocket.chat/app-0.log
    register: rocket_chat_log
    when: (ansible_distribution == "Ubuntu")
          and (ansible_distribution_release == "trusty")

  - name: Ensure the autostarted MongoDB server is stopped
    shell: /usr/sbin/service mongod stop
    when: (ansible_distribution == "Ubuntu")
          and (ansible_distribution_release == "trusty")
          and not (rocket_chat_log.stat.exists)

  - name: Deploy MongoDB service configuration
    template:
      src: "{{ rocket_chat_mongodb_config_template }}"
      dest: /etc/mongod.conf

  - name: Ensure the MongoDB service is started/enabled
    service: name=mongod state=started enabled=yes
    when: rocket_chat_include_mongodb

  - name: Ensure the MongoDB shell replSet script has been deployed
    template:
      src: mongo_rs_initiate.js.j2
      dest: /var/lib/mongodb/mongo_rs_initiate.js
    when: rocket_chat_include_mongodb

  - name: Ensure the MongoDB replSets have been initiated
    shell: >-
      mongo mongo_rs_initiate.js &&
      mongo --eval 'rs.initiate()' &&
      touch .mongo_rs_initialised
    args:
      chdir: /var/lib/mongodb
      creates: /var/lib/mongodb/.mongo_rs_initialised
    when: rocket_chat_include_mongodb
