---
# tasks/mongodb.yml: MongoDB configuration for RocketChat.Ansible
  - include_vars: "{{ item }}"
    with_first_found:
      - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
      - "{{ ansible_distribution }}.yml"
  
  - name: Ensure the MongoDB repository key has been imported
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: 7F0CEB10
    when: ansible_distribution == "Ubuntu"
    tags: repo

  - name: Ensure the MongoDB repository is present
    apt_repository:
      repo: "{{ rocket_chat_mongodb_apt_repo }}"
      state: present
    when: ansible_distribution == "Ubuntu"
    tags: repo

  - name: Ensure MongoDB Server is present
    yum: name={{ item }} state=present
    with_items: "{{ rocket_chat_mongodb_packages }}"
    when: ansible_os_family == "RedHat"

  - name: Ensure MongoDB Server is present
    apt: name={{ item }} state=present
    with_items: "{{ rocket_chat_mongodb_packages }}"
    when: ansible_os_family == "Debian"

  - name: Deploy MongoDB service configuration
    template:
      src: "{{ rocket_chat_mongodb_config_template }}"
      dest: /etc/mongod.conf
    notify: Restart the MongoDB service

  - meta: flush_handlers

  - name: Ensure the MongoDB service is started/enabled
    service: name=mongod state=started enabled=yes
    when: rocket_chat_include_mongodb
