---
# tasks/mongodb.yml: MongoDB configuration for RocketChat.Ansible

  - name: Ensure the MongoDB repository key has been imported
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: 7F0CEB10
    when: ansible_distribution == "Ubuntu"

  - name: Ensure the MongoDB repository is present
    apt_repository:
      repo: deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 multiverse
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: Ensure MongoDB Server is present
    yum: name={{ item }} state=present
    with_items: "{{ rocket_chat_mongodb_packages }}"
    when: ansible_os_family == "RedHat"

  - name: Ensure MongoDB Server is present
    apt: name={{ item }} state=present
    with_items: "{{ rocket_chat_mongodb_packages }}"
    when: ansible_os_family == "Debian"

  - name: Ensure MongoDB replication has been set correctly
    lineinfile:
      line: "replSet=001-rs"
      dest: /etc/mongod.conf
    tags: mongodb

  - name: Ensure the MongoDB service is started/enabled
    service: name=mongod state=started enabled=yes
    when: rocket_chat_include_mongodb
    tags: mongodb

  - name: Ensure the MongoDB shell replSet script has been deployed
    template:
      src: mongo_rs_initiate.js.j2
      dest: /var/lib/mongodb/mongo_rs_initiate.js
    when: rocket_chat_include_mongodb
    tags: mongodb

  - name: Ensure the MongoDB replSets have been initiated
    shell: >-
      mongo mongo_rs_initiate.js &&
      mongo --eval 'rs.initiate()' &&
      touch .mongo_rs_initialised
    args:
      chdir: /var/lib/mongodb
      creates: /var/lib/mongodb/.mongo_rs_initialised
    when: rocket_chat_include_mongodb
    tags: mongodb
