---
# handlers/main.yml: Handlers for RocketChat.Ansible
  - name: Reload the Nginx service
    service: name=nginx state=reloaded

  - name: Upgrade Rocket.Chat
    include: ../tasks/upgrade.yml
    tags:
      - upgrade
